### PR TITLE
Internet Explorer Class Inheritance

### PR DESCRIPTION
**Pull request by paulserraino**

### CODE REVIEW

**Comment by paulserraino** [comment]
`this.set` is undefined b/c IE9 doesnt' like `Object.getPrototypeOf`

https://github.com/goodybag/yokohama/blob/master/src/dependency-set.js#L38

**Comment by L8D** [comment]
niiiiiiiiicceee. But does this fix the entire problem or do we want to include this in all the other projects as well?

**Comment by paulserraino** [comment]
This should work in theory, but i'm still seeing the same issue in cater-web (`this.set` is undefined). I'm going to do some more testing.

**Comment by jrf0110** [comment]
Btw, to get IE to work in my react projects, I had to use:

``` javascript
  "babel": {
    "presets": [
      "es2015-loose",
      "react"
    ],
    "plugins": [
    ...
      "transform-es2015-object-super",
      [
        "transform-es2015-classes",
        {
          "loose": true
        }
      ]
    ]
  },
```

And a polyfill for `Object.setPrototypeOf`

**Comment by paulserraino** [comment]
Nice using `transform-es2015-classes` works great :+1:  @jrf0110. 

@L8D I tested this PR in cater-web and can confirm this fixes the problem. We'll need to include `transform-es2015-classes` in tokyo and cater-web.

**Comment by L8D** [comment]
I think switching to the es2015-loose preset completely would be good. Before upgrading to Babel 6 I had it in loose mode, and non-loose builds added like 300kb to our bundle size

**Comment by paulserraino** [comment]
yikes, i'll switch to the es2015-loose preset

**Pull request merged**
